USE DB_CARLOS_EDUARDO;


INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Thriller', '1982', 1);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Like a Virgin', 1984, 2);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Goodbye Yellow Brick Road', 1973, 3);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Mr. Bad Guy', 1985, 4);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Lemonade', 2016, 5);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('21', 2011, 6);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Laundry Service', 2001, 7);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Transa', 1972, 8);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Good Girl Gone Bad', 2007, 9);

INSERT INTO ALBUMS (TITLE, RELEASE_YEAR, ARTIST_ID)
VALUES ('Divide', 2017, 10);