USE DB_CARLOS_EDUARDO;

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (1, 1);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (1, 3);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (1, 5);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (2, 2);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (2, 4);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (2, 6);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (3, 1);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (3, 7);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (3, 9);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (4, 3);


INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (4, 5);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (4, 8);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (5, 2);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (5, 6);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (5, 10);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (6, 1);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (6, 4);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (6, 7);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (7, 3);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (7, 9);


INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (8, 2);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (8, 5);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (8, 8);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (9, 6);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (9, 10);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (9, 1);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (10, 4);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (10, 7);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (10, 8);

INSERT INTO ARTIST_FOLLOWERS (USER_ID, ARTIST_ID)
VALUES (10, 2);
