SELECT USER , Host FROM mysql.user; 
USE AMAZON;

CREATE TABLE PRODUCT_REVIEWS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	 USER_ID INT ,
	 FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	 PRODUCT_ID INT,
	 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
	 ORDER_ID INT,
	 FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
	 RATING INT,
	 REVIEW_DATE DATE
);