SELECT USER , Host FROM mysql.user; 
USE DB_CARLOS_EDUARDO;
CREATE TABLE FOODS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100),
PRICE DECIMAL(10,2),
CATEGORY_ID INT,
  foreign key (CATEGORY_ID) REFERENCES CATEGORIES (ID) 

);