USE DB_CARLOS_EDUARDO;

# Criando a Tabela USERS
CREATE TABLE USERS(
USERS_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100),
EMAIL VARCHAR (100),
BIRTH_DATE DATE,
IS_PREMIUM BOOLEAN DEFAULT FALSE
);

#Criando a Tabela ARTISTS
CREATE TABLE ARTISTS(
ARTISTS_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100),
COUNTRY  VARCHAR(50)
);

CREATE TABLE GENRES(
GENRES_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100)
);

CREATE TABLE ALBUMS(
ALBUMS_ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(100),
RELEASE_YEAR DATE ,
ARTIST_ID INT,
FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ARTISTS_ID) ON DELETE SET NULL
);

CREATE TABLE SONGS(
SONGS_ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(100),
DURATION_SECONDS INT ,
ALBUM_ID INT,
FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS(ALBUMS_ID) ON DELETE SET NULL
);

CREATE TABLE PLAYLISTS(
PLAYLISTS_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100),
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USERS_ID) ON DELETE SET NULL,
IS_PUBLIC BOOLEAN 
);

CREATE TABLE PLAYLISTS_SONGS(
PLAYLISTS_SONGS_ID INT AUTO_INCREMENT PRIMARY KEY,
PLAYLIST_ID INT,
FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(PLAYLISTS_ID)ON DELETE SET NULL,
SONG_ID INT ,
FOREIGN KEY (SONG_ID) REFERENCES SONGS(SONGS_ID) ON DELETE SET NULL
);

CREATE TABLE PLAYS(
PLAYS_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USERS_ID) ON DELETE SET NULL,
SONG_ID INT ,
FOREIGN KEY (SONG_ID) REFERENCES SONGS(SONGS_ID) ON DELETE SET NULL,
PLAY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE SONG_REVIEWS(
SONG_REVIEWS_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USERS_ID) ON DELETE SET NULL,
SONG_ID INT , 
FOREIGN KEY (SONG_ID) REFERENCES SONGS(SONGS_ID) ON DELETE SET NULL,
RATING INT,
REVIEW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ARTIST_FOLLOWERS(
ARTIST_FOLLOWERS_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USERS_ID) ON DELETE SET NULL,
ARTIST_ID INT , 
FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ARTISTS_ID) ON DELETE SET NULL,
FOLLOW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);