
USE RH_DB_CARLOS_EDUARDO;

/*CREATE TABLE DEPARTAMENTO (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_DEPTO VARCHAR(50)
);

CREATE TABLE NIVEIS_SALARIAIS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NIVEL VARCHAR(20),
SALARIO_MIN DECIMAL(10,2),
SALARIO_MAX DECIMAL(10,2)
);

CREATE TABLE FUNCIONARIOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(20),
SALARIO DECIMAL (10,2),
ID_DEPTO INT,
FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO(ID) ON DELETE CASCADE
);
*/
 
 # EXERCICIO 1 
 SELECT  D.NOME_DEPTO,
 F.NOME
 FROM FUNCIONARIOS F
 RIGHT JOIN DEPARTAMENTO D ON D.ID = F.ID_DEPTO;
 
  # EXERCICIO 2
  
  SELECT F.NOME,
  N.NIVEL
  FROM FUNCIONARIOS F 
  JOIN NIVEIS_SALARIAIS N ON F.SALARIO BETWEEN N.SALARIO_MIN AND N.SALARIO_MAX;
  
    # EXERCICIO 3
  
    SELECT F.NOME,
  N.NIVEL,
  D.NOME_DEPTO
  FROM FUNCIONARIOS F 
  JOIN NIVEIS_SALARIAIS N ON F.SALARIO BETWEEN N.SALARIO_MIN AND N.SALARIO_MAX
  INNER JOIN DEPARTAMENTO D ON D.ID = F.ID_DEPTO 
  HAVING D.NOME_DEPTO = 'Vendas' AND N.NIVEL = 'Pleno';
    



