USE DB_CARLOS_EDUARDO;
select * from COUNTRIES;
SELECT NAME , CONTINENT FROM COUNTRIES;
select * from COUNTRIES WHERE CONTINENT ='América do Norte';
select * from COUNTRIES order by POPULATION ASC;
CREATE USER 'CARLOS_EDUARDO'@'%' identified by 'Ca_305206';
GRANT SELECT ON DB_CARLOS_EDUARDO.COUNTRIES TO 'CARLOS_EDUARDO'@'%';
GRANT ALL privileges ON DB_CARLOS_EDUARDO.COUNTRIES TO 'CARLOS_EDUARDO'@'%';
SHOW GRANTS FOR  'CARLOS_EDUARDO'@'%';
SELECT * FROM COUNTRIES WHERE NAME LIKE '%NI%';

