USE DB_CARLOS_EDUARDO;

#EXERCICIO 1 
SELECT S.NAME,
C.CLASS_NAME,
TEACHERS.NAME AS NOME_PROFESSOR,
TEACHERS.SUBJECT AS DISCIPLINA
FROM STUDENTS S
JOIN CLASSES C ON C.ID = S.CLASS_ID
JOIN TEACHERS ON TEACHERS.ID = C.TEACHER_ID;

#EXERCICIO 2

SELECT STUDENTS.NAME,
GRADES.GRADE,
TEACHERS.SUBJECT
FROM STUDENTS 
JOIN GRADES ON STUDENTS.ID = GRADES.STUDENT_ID
JOIN CLASSES ON STUDENTS.CLASS_ID = CLASSES.ID 
JOIN TEACHERS  ON TEACHERS.ID = CLASSES.TEACHER_ID;

 #EXERCICIO 3
SELECT STUDENTS.NAME,
GRADES.GRADE,
TEACHERS.SUBJECT
FROM STUDENTS 
LEFT JOIN GRADES ON STUDENTS.ID = GRADES.STUDENT_ID
JOIN CLASSES ON STUDENTS.CLASS_ID = CLASSES.ID 
JOIN TEACHERS  ON TEACHERS.ID = CLASSES.TEACHER_ID;

 #EXERCICIO 4
 
 SELECT S.NAME ,
 S.AGE,
 AVG(GRADES.GRADE) AS MEDIA_DO_ALUNO
 FROM  STUDENTS S
 JOIN GRADES ON S.ID = GRADES.STUDENT_ID
 GROUP BY 
 S.ID ,S.NAME , S.AGE
 HAVING AVG(GRADES.GRADE) > (SELECT AVG(GRADE) FROM GRADES) ;
 
  #EXERCICIO 5
   SELECT S.NAME ,
 S.AGE,
 AVG(GRADES.GRADE) AS MEDIA_DO_ALUNO
 FROM  STUDENTS S
 JOIN GRADES ON S.ID = GRADES.STUDENT_ID
 JOIN CLASSES ON S.CLASS_ID = CLASSES.ID
 JOIN TEACHERS ON TEACHERS.ID = CLASSES.TEACHER_ID 
 WHERE TEACHERS.NAME = 'Carlos Silva'
  GROUP BY 
 S.ID ,S.NAME , S.AGE;

    #EXERCICIO 6

SELECT
    c.CLASS_NAME,
    COUNT(s.ID) AS TOTAL_ALUNOS
FROM CLASSES c
INNER JOIN STUDENTS s
    ON c.ID = s.CLASS_ID
GROUP BY c.ID, c.CLASS_NAME
HAVING COUNT(s.ID) > (
    SELECT AVG(QTD_ALUNOS)
    FROM (
        SELECT COUNT(ID) AS QTD_ALUNOS
        FROM STUDENTS
        GROUP BY CLASS_ID
    ) AS MEDIA_POR_TURMA
);

select * FROM STUDENTS