USE AMAZON ;

#  EXERCICIO 1
	SELECT * FROM USERS;

# EXERCICIO 2
	SELECT ID , NAME FROM USERS
    ORDER BY NAME ASC;
    
#EXERCICIO 3
	SELECT EMAIL FROM USERS 
	WHERE EMAIL LIKE '%gmail%';
    
#EXERCICIO 4
	
SELECT * FROM USERS 
WHERE DATA_DE_NASCIMENTO > '2000-01-01';

#EXERCICIO 5
SELECT * FROM CATEGORIES;

#EXERCICIO 6
SELECT * FROM PRODUCTS
WHERE PRICE > 1000;

#EXERCICIO 7
SELECT * FROM PRODUCTS
WHERE PRICE >= 50 AND PRICE <= 200;

#EXERCICIO 8 
SELECT * FROM PRODUCTS 
ORDER BY PRICE DESC;

#EXERCICIO 9
SELECT * FROM PRODUCTS
WHERE CATEGORY_ID = 1;

#EXERCICIO 10
SELECT * FROM PRODUCTS
WHERE NAME LIKE 'A%';

#EXERCICIO 11
SELECT * FROM ORDERS;

#EXERCICIO 12
SELECT * FROM ORDERS
WHERE USER_ID = 10;

#EXERCICIO 13
SELECT * FROM ORDERS
ORDER BY ORDER_DATE DESC;

#EXERCICIO 14
SELECT * FROM ORDER_ITEMS
WHERE QUANTITY > 1;

#EXERCICIO 15
SELECT * FROM ORDER_ITEMS
WHERE PRODUCT_ID = 8;

#EXERCICIO 16
SELECT * FROM PRODUCT_REVIEWS
WHERE RATING > 4 ;

#EXERCICIO 17
SELECT * FROM PRODUCT_REVIEWS
WHERE REVIEW_DATE > ('2024-01-01') AND REVIEW_DATE < ('2024-12-31');


#EXERCICIO 18
SELECT * FROM PRODUCT_REVIEWS
ORDER BY RATING DESC;

#EXERCICIO 19
SELECT * FROM PRODUCTS
WHERE ID NOT IN (
    SELECT PRODUCT_ID
    FROM REVIEWS
);