# Exercicio 21
SELECT * FROM SONGS
WHERE DURATION_SECONDS > 100;

# Exercicio 22
SELECT * FROM SONGS
WHERE GENRE_ID IN( 1 , 2);

# Exercicio 23
SELECT * FROM PLAYLISTS
WHERE IS_PUBLIC = TRUE;

# Exercicio 24
SELECT * FROM SONGS
WHERE TITLE LIKE '%LOVE%';

# Exercicio 25 
SELECT * FROM SONGS 
ORDER BY DURATION_SECONDS ASC;

# Exercicio 26 
SELECT SONGS.TITLE, 
ARTISTS.NAME  
FROM ALBUMS
JOIN SONGS ON SONGS.ALBUM_ID = ALBUMS.ALBUMS_ID
JOIN ARTISTS ON ALBUMS.ARTIST_ID = ARTISTS.ARTISTS_ID;

# Exercicio 27
SELECT USERS.NAME ,
PLAYLISTS.NAME
FROM USERS 
JOIN PLAYLISTS ON PLAYLISTS.PLAYLISTS_ID = USERS.USERS_ID;

# Exercicio 28
SELECT  SONGS.TITLE,
GENRES.NAME
FROM SONGS
JOIN GENRES ON GENRES.GENRES_ID = SONGS.SONGS_ID;

# Exercicio 29
select* FROM ARTIST_FOLLOWERS;
SELECT USERS.NAME,
ARTIST_FOLLOWERS.ARTIST_ID
FROM USERS 
JOIN ARTIST_FOLLOWERS ON ARTIST_FOLLOWERS.ARTIST_FOLLOWERS_ID = USERS.USERS_ID
WHERE IS_PREMIUM = TRUE;

# Exercicio 30
SELECT SONGS.TITLE, SONGS.DURATION_SECONDS ,SONGS.SONGS_ID,
SONG_REVIEWS.RATING
FROM SONGS
 LEFT JOIN SONG_REVIEWS ON SONG_REVIEWS.SONG_REVIEWS_ID = SONGS.SONGS_ID
 WHERE DURATION_SECONDS > 200 OR SONG_REVIEWS.RATING < 3; 
 
 # Exercicio 31
 SELECT USERS.NAME , SONGS.TITLE , PLAYS.PLAY_DATE
 FROM PLAYS
 JOIN USERS ON USERS.USERS_ID = PLAYS.USER_ID
 JOIN SONGS ON SONGS.SONGS_ID = PLAYS.SONG_ID;