USE GAME_PLATFORM;

# -- EXERCÍCIO 1
SELECT * FROM GAMES
WHERE PRICE > ( SELECT AVG (PRICE) FROM GAMES);

# -- EXERCÍCIO 2
SELECT USERS.NAME ,
PURCHASES.GAME_ID,
GAMES.TITLE
FROM PURCHASES 
JOIN USERS ON USERS.ID = PURCHASES.USER_ID
JOIN GAMES ON GAMES.ID = PURCHASES.GAME_ID;

# -- EXERCÍCIO 3

SELECT REVIEWS.SCORE,
GAMES.TITLE
FROM REVIEWS
JOIN GAMES ON GAMES.ID = GAME_ID;

# -- EXERCÍCIO 4

SELECT GAMES.TITLE,
GAMES.PRICE ,
PURCHASES.GAME_ID

FROM PURCHASES 
JOIN USERS ON USERS.ID = PURCHASES.USER_ID
JOIN GAMES ON GAMES.ID = PURCHASES.GAME_ID
WHERE PRICE > ( SELECT AVG (PRICE) FROM GAMES);

# -- EXERCÍCIO 5
SELECT USERS.NAME,
USERS.COUNTRY,
USERS.AGE
FROM PURCHASES
RIGHT JOIN USERS ON PURCHASES.USER_ID = USERS.ID 
WHERE PURCHASES.USER_ID IS NULL;

# -- EXERCÍCIO 6
SELECT 
    G.ID ,
    G.TITLE,
    G.GENRE,
    G.PRICE,
   AVG(R.SCORE) AS Média_Nota
FROM GAMES G
INNER JOIN REVIEWS R 
    ON G.ID = R.GAME_ID
GROUP BY 
    G.ID, G.TITLE, G.GENRE, G.PRICE
HAVING 
    AVG(R.SCORE) > 4;