USE DB_CARLOS_EDUARDO;

INSERT INTO GENRES (NAME)
VALUES ('Pop');

INSERT INTO GENRES (NAME)
VALUES ('Rock');

INSERT INTO GENRES (NAME)
VALUES ('R&B');

INSERT INTO GENRES (NAME)
VALUES ('Latin Pop');

INSERT INTO GENRES (NAME)
VALUES ('MPB');