USE DB_CARLOS_EDUARDO;

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (1, 1);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (1, 2);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (2, 3);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (2, 4);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (3, 5);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (3, 6);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (4, 7);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (4, 8);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (5, 9);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (5, 10);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (6, 11);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (6, 12);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (7, 13);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (7, 14);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (8, 15);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (8, 16);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (9, 17);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (9, 18);


INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (10, 19);

INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONG_ID)
VALUES (10, 20);