USE DB_CARLOS_EDUARDO;

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('Pop Hits', 1, 1);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('Rock Classics', 2, 0);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('R&B Vibes', 3, 1);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('Latin Pop Essentials', 4, 0);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('MPB Classics', 5, 1);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('Pop Internacional', 6, 0);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('Rock Legends', 7, 1);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('R&B & Soul', 8, 0);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('Latin Pop Hits', 9, 1);

INSERT INTO PLAYLISTS (NAME, USER_ID, IS_PUBLIC)
VALUES ('MPB Essencial', 10, 0);

