SELECT USER , Host FROM mysql.user; 
USE DB_CARLOS_EDUARDO;

# select * from FOODS;
#Junta ambas as Tabelas E realiza um retorno com uma condição WHERE
	select CATEGORIES.NAME, FOODS.NAME , FOODS.PRICE
	FROM CATEGORIES
	INNER JOIN FOODS
	ON CATEGORIES.ID = FOODS.CATEGORY_ID
	WHERE CATEGORIES.NAME = 'FAST FOOD';
		# ORDER BY FOODS.PRICE DESC;
   
	DELETE FROM FOODS WHERE NAME = 'Cake'; 
    
    
 select * from FOODS;
	 #LINHA DEDICADA A APAGAR OS DADOS DA TABELA FOODS QUE TEM O VALOR MENOR QUE 10 
	 # delete from FOODS WHERE PRICE < 10; 
     
   # lISTA OS DADOS DA TABELA FOODS COM VALOR MENOR QUE 15 
	SELECT *FROM FOODS WHERE PRICE < 15;
    SELECT *FROM FOODS WHERE PRICE < 40 AND CATEGORY_ID = 1;
    SELECT *FROM FOODS WHERE CATEGORIES.NAME in ('FAST FOOS');
    SELECT * FROM FOODS ORDER BY PRICE desc;
    
    

 
 


 
 
