USE DB_CARLOS_EDUARDO;

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (1, 1, 5);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (2, 2, 4);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (3, 3, 5);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (4, 4, 3);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (5, 5, 4);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (6, 6, 5);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (7, 7, 3);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (8, 8, 4);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (9, 9, 5);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (10, 10, 4);


INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (1, 11, 5);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (2, 12, 3);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (3, 13, 4);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (4, 14, 5);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (5, 15, 2);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (6, 16, 4);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (7, 17, 5);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (8, 18, 3);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (9, 19, 4);

INSERT INTO SONG_REVIEWS (USER_ID, SONG_ID, RATING)
VALUES (10, 20, 5);

