USE DB_CARLOS_EDUARDO;

-- Thriller (Michael Jackson) | ALBUM_ID = 1
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Thriller', 357, 1);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Billie Jean', 294, 1);


-- Like a Virgin (Madonna) | ALBUM_ID = 2
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Like a Virgin', 218, 2);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Material Girl', 240, 2);


-- Goodbye Yellow Brick Road (Elton John) | ALBUM_ID = 3
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Goodbye Yellow Brick Road', 194, 3);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Candle in the Wind', 220, 3);


-- Mr. Bad Guy (Freddie Mercury) | ALBUM_ID = 4
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Living on My Own', 218, 4);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Love Me Like There’s No Tomorrow', 247, 4);


-- Lemonade (Beyoncé) | ALBUM_ID = 5
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Formation', 206, 5);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Sorry', 233, 5);


-- 21 (Adele) | ALBUM_ID = 6
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Rolling in the Deep', 228, 6);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Someone Like You', 285, 6);


-- Laundry Service (Shakira) | ALBUM_ID = 7
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Whenever, Wherever', 196, 7);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Underneath Your Clothes', 225, 7);


-- Transa (Caetano Veloso) | ALBUM_ID = 8
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('You Don’t Know Me', 293, 8);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('It’s a Long Way', 430, 8);


-- Good Girl Gone Bad (Rihanna) | ALBUM_ID = 9
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Umbrella', 276, 9);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Don’t Stop the Music', 267, 9);


-- Divide (Ed Sheeran) | ALBUM_ID = 10
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Shape of You', 233, 10);

INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Perfect', 263, 10);

-- Thriller (Michael Jackson) | ALBUM_ID = 1
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Beat It', 258, 1);


-- Like a Virgin (Madonna) | ALBUM_ID = 2
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Dress You Up', 251, 2);


-- Goodbye Yellow Brick Road (Elton John) | ALBUM_ID = 3
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Bennie and the Jets', 323, 3);


-- Mr. Bad Guy (Freddie Mercury) | ALBUM_ID = 4
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('I Was Born to Love You', 206, 4);


-- Lemonade (Beyoncé) | ALBUM_ID = 5
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Hold Up', 221, 5);


-- 21 (Adele) | ALBUM_ID = 6
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Set Fire to the Rain', 242, 6);


-- Laundry Service (Shakira) | ALBUM_ID = 7
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('The One', 223, 7);


-- Transa (Caetano Veloso) | ALBUM_ID = 8
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Nine Out of Ten', 520, 8);


-- Good Girl Gone Bad (Rihanna) | ALBUM_ID = 9
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Take a Bow', 229, 9);


-- Divide (Ed Sheeran) | ALBUM_ID = 10
INSERT INTO SONGS (TITLE, DURATION_SECONDS, ALBUM_ID)
VALUES ('Castle on the Hill', 261, 10);

