

SELECT PRODUCTS.NAME AS PRODUTOS,
SUPPLIER.NAME AS FORNECEDORES
FROM SUPPLIER S
INNER JOIN  PRODUCTS ON PRODUCTS.SUPPLIER_ID = SUPPLIER.ID;

SELECT PRODUCTS.NAME,
SALES.QUANTITY,
SALES.SALE_DATE
FROM SALES S
JOIN S ON S.PRODUCTS_ID = PRODUCTS.PRUDUCTS_ID;

SELECT PRODUCTS.NAME,
PRODUCTS.PRICE,
SALES.QUANTIDADE,
SUPPLIER.NAME 
FROM PRODUCTS P 
JOIN SALES  ON P.ID = SALES.PRODUCTS_ID
JOIN SUPPLIER  ON SUPPLIER.ID = P.SUPPLIER_ID;

SELECT  PRODUCTS.NAME,
PRODUCTS.PRICE,
PRODUCTS.QUANTITY,
SUPPLIER.NAME S
FROM PRODUCTS P 
JOIN  S ON S.ID = P.SUPPLIER_ID 
WHERE P.QUANTITY <= 30 ;
 
 ###################################
 USE PRICE_CLASSIFICATION_DB;
 
 SELECT PRODUCTS.NAME,
 PRODUCTS.PRICE,
 PRICE_RANGES.RANGE_NAME
 FROM  PRODUCTS
 JOIN PRICE_RANGES 
 ON PRODUCTS.PRICE BETWEEN PRICE_RANGES.PRICE_MIN AND PRICE_RANGES.PRICE_MAX
 ORDER BY PRODUCTS.PRICE ASC;
 
 SELECT * FROM PRODUCTS;
 SELECT * FROM PRICE_RANGES ;
 
 ####################################
 

 